CREATE TABLE links (
    id SERIAL NOT NULL PRIMARY KEY,
    shortened VARCHAR NOT NULL UNIQUE,
    original TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc')
)
